# Generated by Django 4.1.2 on 2022-11-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SoundRecorderApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="language",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
